### ISSUE TITLE
Improving 3D Mapping 

### ISSUE THREAD

**Issue by ghost** [MohitShridhar/shield_slam#1]
The localization (trajectory) is performing quite good. Congratulations.  
However, do you have some insights about how to improve the mapping ?

**Comment by MohitShridhar** [comment]
Thanks @djebm2 ! Our system is rather primitive. I would suggest reading up on [ORB-SLAM](http://webdiis.unizar.es/~raulmur/MurMontielTardosTRO15.pdf), which greatly inspired our work. Some of the main contributions listed in the paper will help you improve the tracking. You might even want to checkout this new [android port](https://github.com/castoryan/ORB-SLAM-Android)
